# https://stackoverflow.com/questions/63959555/assigning-aws-cloudformation-output-variables-in-azure-devops-pipelines
trigger: none
pr: none

jobs:
- job: myJob
  timeoutInMinutes: 10
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: template.yaml
    parameters:
      name: 'lambdaNumbertOneFunctionName'
      arn: 'lambdaNumberOneFunctionArn'
      value: 'value-1'
  - template: template.yaml
    parameters:
      name: 'lambdaNumberTwoFunctionName'
      arn: 'lambdaNumberTwoFunctionArn'
      value: 'value-2'
  - bash: |
      echo 'lambdaNumbertOneFunctionName - $(lambdaNumbertOneFunctionName)'
      echo 'lambdaNumberOneFunctionArn - $(lambdaNumberOneFunctionArn)'
      echo 'lambdaNumberTwoFunctionName - $(lambdaNumberTwoFunctionName)'
      echo 'lambdaNumberTwoFunctionArn - $(lambdaNumberTwoFunctionArn)'
  - bash: |
      echo "##vso[task.setvariable variable=sauce;]crushed tomatoes"
      echo "##vso[task.setvariable variable=secretSauce;issecret=true]crushed tomatoes with garlic"
      echo "##vso[task.setvariable variable=outputSauce;isoutput=true]canned goods"
    name: SetVars

  - bash: |
      echo "Non-secrets automatically mapped in, sauce is $SAUCE"
      echo "Secrets are not automatically mapped in, secretSauce is $SECRETSAUCE"
      echo "You can use macro replacement to get secrets, and they'll be masked in the log: $(secretSauce)"
      echo "Future jobs can also see $OUTPUTSAUCE"
      echo "Future jobs can also see $(SetVars.outputSauce)"