trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
- job: RunOnEveryEnv
  strategy:
    matrix:
       uat:
          env: 'uat'
       prod:
          env: 'prod'
  steps:
  - script: echo '$(env)'
  - ${{ if eq(variables['env'], 'uat')}}:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'rg-the-code-manual'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: az account show
    - template: templates/azure-cli.yaml
      parameters:
        serviceConnectionName: 'rg-the-code-manual'
  - ${{ elseif eq(variables['env'], 'prod')}}:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'full-subscription'
        scriptType: pscore
        scriptLocation: 'inlineScript'
        inlineScript: az account show
    - template: templates/azure-cli.yaml
      parameters:
        serviceConnectionName: 'full-subscription'