trigger:
  branches:
    include:
      - master
  paths:
    include:
      - cache-ruby-gems/*

pr: none

pool:
  vmImage: 'macOS-latest'

variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle

steps:
- task: Cache@2
  inputs:
    key: 'gems | "$(Agent.OS)" | Gemfile.lock'
    restoreKeys: | 
      gems | "$(Agent.OS)"
      gems
    path: $(BUNDLE_PATH)
    cacheHitVar: CACHE_RESTORED
  displayName: Cache gems

- bash: bundle install --gemfile cache-ruby-gems/Gemfile
  displayName: 'Install Bundle'
  condition: ne(variables.CACHE_RESTORED, 'true')

- bash: brew update && brew install imagemagick
  displayName: 'Install ImageMagick'
- bash: brew install sonar-scanner
  displayName: "Install sonar-scanner"