parameters:
- name: serviceName
  type: string

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - script: |
        name="${{ parameters.serviceName }}"
        lowercase_name=$(echo "$name" | tr '[:upper:]' '[:lower:]')
        echo "##vso[task.setvariable variable=lowerName;]'$lowercase_name'"

    - script: echo $(lowerName)
    - script: echo $(lowerName2)