parameters:
- name: serviceName
  type: string

stages:
- stage: A
  variables:
    lowerName2: ${{ lower(parameters.serviceName) }}
  jobs:
  - job: A1
    steps:
    - script: |
        echo "${{ lower(parameters.serviceName) }}"
        name=${{ lower(parameters.serviceName) }}
        echo "##vso[task.setvariable variable=lowerName;]$name"

    - script: echo $(lowerName)
    - script: echo $(lowerName2)