
trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    include:
    - build-docker-image/SampleAppForDocker/*
    exclude:
    - build-docker-image/SampleAppForDocker/*.ymal

variables:
  imageName: 'SampleAppForDocker'
  DOCKER_BUILDKIT: 1

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: devopsmanual-acr

- task: Docker@2
  displayName: Build and Push
  inputs:
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: build-docker-image/SampleAppForDocker/DOCKERFILE
    tags: |
      build-with-build-kit

- task: Docker@2
  displayName: Logout of ACR
  inputs:
    command: logout
    containerRegistry: devopsmanual-acr